export 'package:app4/screens/help_screen.dart';
export 'package:app4/screens/politics_screen.dart';
export 'package:app4/screens/favorites_screen.dart';
export 'package:app4/screens/history_screen.dart';
export 'package:app4/screens/onboarding_screen.dart';
export 'package:app4/screens/onboarding_screen1.dart';
export 'package:app4/screens/onboarding_screen2.dart';
export 'package:app4/screens/onboarding_screen3.dart';
export 'package:app4/screens/forTile.dart';
export 'package:app4/screens/gps_access_screen.dart';
export 'package:app4/screens/loading_initial_screen.dart';
export 'package:app4/screens/loading_screen.dart';
export 'package:app4/screens/loading_screen.dart';
export 'package:app4/screens/map_screen.dart';
export 'package:app4/screens/register_screen.dart';
export 'package:app4/screens/restore_password_screen.dart';
export 'package:app4/screens/settings_screen.dart';
export 'package:app4/screens/splash.dart';

